Repository ejh243/BrainFANS, pull requests merged in 2024-05, with the labels that each got.

#129 Fix DCF issues
  .github/linters/.lintr
Labels: bug

#119 remove redundant script for changing file permissions
  general/jobSubmission/filePermissions.sh
Labels: bug

#93 Merge conflict correction
  documentation/docs/Developer-information/merge-conflicts.md
  documentation/package-lock.json
  documentation/package.json
Labels: documentation, web development

#94 Branch creation guide update
  documentation/docs/Developer-information/Contributing-to-documentation/Creating-new-branch.md
  documentation/docs/Developer-information/Contributing-to-repository/Creating-new-branch.md
  documentation/docs/Developer-information/Contributing-to-repository/Getting-latest-version-of-BrainFANS.md
Labels: documentation

#134 change linters used
  .github/linters/.lintr
Labels: enhancement

#140 as.character(sample IDs) so nFACS no longer gives N/As
  array/DNAm/preprocessing/clusterCellTypes.r
Labels: bug

#63 Fix crlf eol
  array/SNPArray/PennCNVEURonly.sh
  sequencing/DNAhydroxy/jobSubmission/peakCalling5hmCIncreasingSampleSizes.sh
Labels: bug, All
