Repository ejh243/BrainFANS, pull requests merged in 2024-12, with the labels that each got.

#264 refactor: use readManifest function from cdegUtilities
  array/DNAm/preprocessing/calcQCMetrics.r
  array/DNAm/preprocessing/clusterCellTypes.r
  array/DNAm/preprocessing/normalisation.r
  array/DNAm/preprocessing/rmarkdownChild/ctCheck.rmd
Labels: refactor

#280 MethQC error file messages
  array/DNAm/preprocessing/CETYGOdeconvolution.r
  array/DNAm/preprocessing/QC.rmd
  array/DNAm/preprocessing/calcQCMetrics.r
  array/DNAm/preprocessing/checkColnamesSampleSheet.r
  array/DNAm/preprocessing/clusterCellTypes.r
  array/DNAm/preprocessing/filterToAutosomes.r
  array/DNAm/preprocessing/loadDataGDS.r
  array/DNAm/preprocessing/normalisation.r
Labels: good first issue, DNAm, documentation

#247 fix: use levels over unique
  array/DNAm/preprocessing/QC.rmd
Labels: bug, needs reviewer
