Repository ejh243/BrainFANS, pull requests merged in 2024-03, with the labels that each got.

#64 fix functionsR load
  array/DNAm/preprocessing/loadDataGDS.r
Labels: bug

#56 Code review upgrade
  documentation/docs/Developer-information/Code-review/Best-practices.md
  documentation/docs/Developer-information/Code-review/Code-examples.md
  documentation/docs/Developer-information/Code-review/Conducting-a-code-review.md
Labels: web development

#65 create new initiateDataFolders.sh script
  general/jobSubmission/initiateDataFolders.sh
Labels: enhancement

#59 Merge conflict section
  documentation/docs/Developer-information/Contributing-to-repository/Create-pull-request.md
  documentation/docs/Developer-information/Contributing-to-repository/Finalise-pull-request.md
  documentation/docs/Developer-information/merge-conflicts.md
  documentation/src/css/custom.css
  documentation/static/merge-conflicts/github-merge-conflicts.png
Labels: web development
