Repository ejh243/BrainFANS, pull requests merged in 2024-09, with the labels that each got.

#182 refactor: remove nested c calls
  array/DNAm/preprocessing/QC.rmd
Labels: needs reviewer, refactor

#163 Resolve high severity vulnerabilities
  documentation/package-lock.json
  documentation/package.json
Labels: security, important

#153 Use full file paths instead of globs in s/f tests
  sequencing/BSSeq/preprocessing/calcQCMetrics.sh
  sequencing/BSSeq/preprocessing/progressReport.sh
  sequencing/ChIPSeq/preprocessing/calcENCODEQCMetrics.sh
  sequencing/ChIPSeq/preprocessing/calcFrip.sh
  sequencing/ChIPSeq/preprocessing/progressReport.sh
Labels: needs reviewer, refactor

#209 refactor: checkRconfig
  array/DNAm/preprocessing/checkRconfigFile.r
Labels: refactor

#208 184 check r config
  array/DNAm/config/config.example.r
  array/DNAm/preprocessing/CETYGOdeconvolution.r
  array/DNAm/preprocessing/checkRconfigFile.r
  array/DNAm/preprocessing/clusterCellTypes.r
  array/DNAm/preprocessing/jobSubmission/1_runDNAmQC.sh
Labels: enhancement

#219 fix: PCs identified text showing incorrect number
  array/DNAm/preprocessing/QC.rmd
Labels: bug, DNAm, needs reviewer

#220 Remove tech var and bio var variables
  array/DNAm/config/config.example.r
  array/DNAm/preprocessing/QC.rmd
  array/DNAm/preprocessing/checkRconfigFile.r
Labels: enhancement, DNAm

#218 fix: predictedduplicates containing empty strings
  array/DNAm/preprocessing/QC.rmd
Labels: bug, DNAm

#217 Add repository version to QC rmarkdown
  array/DNAm/preprocessing/QC.rmd
  array/DNAm/preprocessing/jobSubmission/1_runDNAmQC.sh
Labels: enhancement, DNAm

#227 Make the git tag only show the version number
  array/DNAm/preprocessing/jobSubmission/1_runDNAmQC.sh
Labels: bug
